#!/usr/bin/env bash
path="/home/arya/qmk_firmware/keyboards/redox_custom/"
mkdir $path
sudo mount --bind /home/arya/Documents/workspace/redox-qmk/kb $path
qmk flash -kb redox_custom/rev1/base -km std
sudo umount $path
